package HTTP::Throwable::Role::Status::UseProxy;
use Moose::Role;

with(
  'HTTP::Throwable',
  'HTTP::Throwable::Role::Redirect',
  'HTTP::Throwable::Role::BoringText',
);

sub default_status_code { 305 }
sub default_reason      { 'Use Proxy' }

no Moose::Role; 1;

__END__

# ABSTRACT: 305 Use Proxy

=head1 DESCRIPTION

The requested resource MUST be accessed through the proxy given
by the Location field. The Location field gives the URI of the
proxy. The recipient is expected to repeat this single request
via the proxy. 305 responses MUST only be generated by origin
servers.

=attr location

This is a required string, which will be used in the Location header
when creating a PSGI response.



